FROM python:3.6-alpine
LABEL maintainer="Craig Derington <cderington@championsg.com>"
RUN apk update && apk upgrade
RUN apk add --no-cache --virtual build-deps build-base gcc python3-dev openssl-dev \
    libressl-dev libffi-dev screen curl
WORKDIR /code
COPY . /code
RUN pip3 install --no-cache-dir -r requirements.txt
CMD ["celery", "-A", "stalks.celery", "worker", "-l", "INFO", "-n", "worker0@%h", "-c", "4"]